### ISSUE TITLE
remove elminda-specific information

### ISSUE THREAD

**Issue by jbustamovej** [royeectu/kube-sso#1]
@royeectu you have some Elminda-specific information in here for idp, client_id, and post_url. It seems that these values need to be extracted to command-line arguments to kube_sso.

**Comment by royeectu** [comment]
Thanks @jbustamovej , I have plans to add some CLI arguments

**Comment by royeectu** [comment]
@jbustamovej, check out the following commit which now supports any IDP server: 
[commit](https://github.com/royeectu/kube-sso/commit/0aef8747b72f4d52f853cfb4a8b9a05a68ff074c)
